"""Add is_whitelisted field on game

Revision ID: 11ab24a171c5
Revises: ebe74b0f82bb
Create Date: 2023-06-17 12:41:27.012598

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '11ab24a171c5'
down_revision = 'ebe74b0f82bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('is_whitelisted', sa.Boolean(), server_default="false", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'is_whitelisted')
    # ### end Alembic commands ###
