"""empty message

Revision ID: 1baecc80394f
Revises: 61d92faf9de0
Create Date: 2023-07-02 14:31:31.296888

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '1baecc80394f'
down_revision = '61d92faf9de0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mappick_selected_by_id_fkey', 'mappick', type_='foreignkey')
    op.create_foreign_key(None, 'mappick', 'match_team', ['selected_by_id'], ['id'])
    op.create_unique_constraint(None, 'match', ['map_pick_process_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'match', type_='unique')
    op.drop_constraint(None, 'mappick', type_='foreignkey')
    op.create_foreign_key('mappick_selected_by_id_fkey', 'mappick', 'team', ['selected_by_id'], ['id'])
    # ### end Alembic commands ###
