"""Add team to player

Revision ID: 2c203c71192b
Revises: 71d351e515f3
Create Date: 2023-05-17 13:00:13.203888

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '2c203c71192b'
down_revision = '71d351e515f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'player', 'team', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'player', type_='foreignkey')
    op.drop_column('player', 'team_id')
    # ### end Alembic commands ###
