"""empty message

Revision ID: 61d92faf9de0
Revises: 8cf57054efcb
Create Date: 2023-07-02 13:36:26.208680

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '61d92faf9de0'
down_revision = '8cf57054efcb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match_team', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match_team', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
