"""empty message

Revision ID: 677e913d3837
Revises: 9ce64b37a9f8
Create Date: 2023-07-30 12:30:11.357227

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '677e913d3837'
down_revision = '9ce64b37a9f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('started_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'started_at')
    # ### end Alembic commands ###
