"""empty message

Revision ID: 8cf57054efcb
Revises: c83660442760
Create Date: 2023-06-30 12:36:06.459273

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '8cf57054efcb'
down_revision = 'c83660442760'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True))
    op.add_column('player', sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('player', sa.Column('verification_code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'verification_code')
    op.drop_column('player', 'password')
    op.drop_column('player', 'last_seen')
    # ### end Alembic commands ###
