"""empty message

Revision ID: 9ce64b37a9f8
Revises: 1baecc80394f
Create Date: 2023-07-02 15:02:18.592102

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9ce64b37a9f8'
down_revision = '1baecc80394f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('map_pick_process', 'turn_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('map_pick_process', 'turn_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
