"""Add created_at to game

Revision ID: a4c87f85bb06
Revises: 11ab24a171c5
Create Date: 2023-06-18 16:59:05.667382

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a4c87f85bb06'
down_revision = '11ab24a171c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('created_at', sa.DateTime(), server_default="2000-01-01", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'created_at')
    # ### end Alembic commands ###
