"""empty message

Revision ID: c4e19d057f07
Revises: da203fb2b748
Create Date: 2023-05-25 11:55:04.631498

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c4e19d057f07'
down_revision = 'da203fb2b748'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player', 'uuid',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.drop_constraint('player_uuid_key', 'player', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('player_uuid_key', 'player', ['uuid'])
    op.alter_column('player', 'uuid',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###
