"""empty message

Revision ID: c83660442760
Revises: ed3ce08cb393
Create Date: 2023-06-24 22:52:02.270266

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c83660442760'
down_revision = 'ed3ce08cb393'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('round', sa.Column('win_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('round', 'win_reason')
    # ### end Alembic commands ###
