"""empty message

Revision ID: dcca1a87e8fd
Revises: 677e913d3837
Create Date: 2023-07-30 14:52:54.083893

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'dcca1a87e8fd'
down_revision = '677e913d3837'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_queue', sa.Column('size', sa.Integer(), nullable=False, server_default='10'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_queue', 'size')
    # ### end Alembic commands ###
