"""empty message

Revision ID: ed3ce08cb393
Revises: a4c87f85bb06
Create Date: 2023-06-18 21:54:11.744763

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'ed3ce08cb393'
down_revision = 'a4c87f85bb06'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), server_default="not set", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'username')
    # ### end Alembic commands ###
